name: tcc_bag_finder
description: "Bag Finder"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.4.0
  flutter_modular: ^6.3.4
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.2.0+3
  dartz: ^0.10.1
  logger: ^2.4.0
  collection: ^1.18.0
  brazillian: ^2.0.0
  random_password_generator: ^0.2.1
  uuid: ^4.5.1
  event_bus: ^2.0.1
  dropdown_button2: ^2.3.9
  path_provider: ^2.1.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/flying-around.png
    - images/group-interrogation.png
    - images/luggage-two-persons.png
    - images/paper-macute.png
    - images/two-persons.png
