name: bag_finder
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.17.7
  flutter_modular: ^6.3.2
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  logger: ^2.4.0
  provider: ^6.1.1
  dropdown_button2: ^2.3.9
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  dartz: ^0.10.1
  event_bus: ^2.0.1
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true  
  uses-material-design: true
  assets:
    - images/flying-around.png
    - images/group-interrogation.png
    - images/luggage-two-persons.png
    - images/paper-macute.png
    - images/two-persons.png

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated