// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ILXDIdSsaGbclw95OSgAIWJ6d6QJbZo',
    appId: '1:707908197295:web:168257407193decbfcad5a',
    messagingSenderId: '707908197295',
    projectId: 'bagfinder-b7b52',
    authDomain: 'bagfinder-b7b52.firebaseapp.com',
    databaseURL: 'https://bagfinder-b7b52-default-rtdb.firebaseio.com',
    storageBucket: 'bagfinder-b7b52.firebasestorage.app',
    measurementId: 'G-FDLSX9NB3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Xdy4w1rpA5QhITIvLG2aGkxSBRkKumg',
    appId: '1:707908197295:android:0259f1dc8604819afcad5a',
    messagingSenderId: '707908197295',
    projectId: 'bagfinder-b7b52',
    databaseURL: 'https://bagfinder-b7b52-default-rtdb.firebaseio.com',
    storageBucket: 'bagfinder-b7b52.firebasestorage.app',
  );
}
